blank_issues_enabled: false
contact_links:
  - name: Reporting a Vulnerability
    url: https://docs.kubara.io/latest-stable/6_reference/security/
    about: Please report security vulnerabilities here.