---
name: Bug or Feature Request
description: Report a bug, suggest a feature, or ask a question related to Kubara
title: "[Issue]: "
labels: ["triage"]
assignees: []
body:
  - type: dropdown
    id: type-of-issue
    attributes:
      label: 🧩 Type of Issue
      options:
        - 🐛 Bug
        - ✨ Feature request
        - ❓ Question or clarification
        - 🧪 Improvement or refactor
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: "📝 Description"
      description: |
        Please read first <a target="_blank" href="https://github.com/kubara-io/kubara/blob/main/CONTRIBUTING.md">how to contribute to Kubara</a>.
      placeholder: |
        Briefly describe the issue or request. What is the problem, question, or improvement you're raising?
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: 📎 Additional Context / Logs
      description: Paste logs, screenshots, or links to related docs or issues here.

  - type: textarea
    id: steps
    attributes:
      label: 🧪 Steps to Reproduce (for bugs)
      description: List clear steps to reproduce the issue.
      placeholder: |
        1. Run `kubara init`
        2. Apply config X
        3. Observe error Y

  - type: textarea
    id: environment
    attributes:
      label: 💻 Environment (for bugs)
      description: Provide relevant environment details.
      placeholder: |
        - Kubara version: v1.4.2
        - Kubernetes version: 1.28 (EKS)
        - Helm version: 3.13
        - Platform: kind
        - OS/Arch: Ubuntu 22.04 / amd64

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      options:
        - label: I have searched existing issues
          required: true
        - label: I am using the latest version of Kubara
        - label: The issue is reproducible
        - label: This is not a duplicate
