---
apiVersion: kubara.io/v1alpha1
kind: ServiceDefinition
metadata:
  name: velero
  annotations:
    kubara.io/category: storage
spec:
  chartPath: velero
  status: disabled
  clusterTypes:
    - hub
    - spoke
  configSchema:
    type: object
    properties:
      fsBackupEnabled:
        type: boolean
        default: true
        description: "If true, enables file-system backups via the node agent. If false, switches to CSI volume snapshots."
      s3BucketName:
        type: string
        minLength: 1
      s3BucketRegion:
        type: string
        minLength: 1
      s3Url:
        type: string
        format: uri
