---
apiVersion: v1
stringData:
  enableLfs: "true"
  forceHttpBasicAuth: "true"
  insecure: "false"
  password: "${ARGOCD_GIT_PAT_OR_PASSWORD}"
  username: "${ARGOCD_GIT_USERNAME}"
  name: https-init-repo-access
  url: ${ARGOCD_GIT_HTTPS_URL}
  project: "${PROJECT_NAME}-${PROJECT_STAGE}"
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: https-init-repo-access
  namespace: argocd
type: Opaque
---
apiVersion: v1
data:
  .dockerconfigjson: ${DOCKERCONFIG_BASE64}
kind: Secret
metadata:
  name: image-pull-secret
  namespace: argocd
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
stringData:
  enableOCI: "true"
  url: ${ARGOCD_HELM_REPO_URL}
  name: helm-chart-repository
  password: ${ARGOCD_HELM_REPO_PASSWORD}
  project: ${PROJECT_NAME}-${PROJECT_STAGE}
  type: helm
  username: ${ARGOCD_HELM_REPO_USERNAME}
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: helm-charts-repository
  namespace: argocd
type: Opaque
---
apiVersion: v1
data:
  username: ${SECRETS_MANAGER_USERNAME_BASE64}
  password: ${SECRETS_MANAGER_PASSWORD_BASE64}
kind: Secret
metadata:
  name: stackit-secrets-manager-cred
  namespace: external-secrets
type: Opaque
---
apiVersion: v1
items:
  - apiVersion: external-secrets.io/v1
    kind: ClusterSecretStore
    metadata:
      labels:
        argocd.argoproj.io/instance: ${PROJECT_NAME}-external-secrets
      name: "${PROJECT_NAME}-${PROJECT_STAGE}"
    spec:
      provider:
        vault:
          auth:
            userPass:
              path: userpass
              secretRef:
                key: password
                name: stackit-secrets-manager-cred
                namespace: external-secrets
              username: ${SECRETS_MANAGER_USERNAME}
          path: ${SECRETS_MANAGER_PATH}
          server: ${SECRETS_MANAGER_URL}
          version: v2
kind: List
metadata:
  resourceVersion: ""
