---
apiVersion: v1
data:
  .dockerconfigjson: ${DOCKERCONFIG_BASE64}
kind: Secret
metadata:
  name: image-pull-secret
  namespace: external-secrets
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
data:
  username: ${WORKER_SECRETS_MANAGER_USERNAME_BASE64}
  password: ${WORKER_SECRETS_MANAGER_PASSWORD_BASE64}
kind: Secret
metadata:
  name: stackit-secrets-manager-cred
  namespace: external-secrets
type: Opaque
